useTabs: false
arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
proseWrap: always
singleQuote: false
tabWidth: 4
trailingComma: "all"

overrides:
    - files: "*.sol"
      options:
          compiler: "0.8.18"
          tabWidth: 4
    - files: "*.ts"
      options:
          importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
          importOrderParserPlugins: ["typescript"]
          importOrderSeparation: true
          importOrderSortSpecifiers: true
    - files: "*.json"
    - files: "./*.{js,json,yml,ts}"
      options:
          tabWidth: 4
