/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILoanCore,
  ILoanCoreInterface,
} from "../../../../../@arcadexyz/v2-contracts/contracts/interfaces/ILoanCore";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FeesClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "repaidAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "remBalance",
        type: "uint256",
      },
    ],
    name: "InstallmentPaymentReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "LoanClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "durationSecs",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "deadline",
            type: "uint32",
          },
          {
            internalType: "uint24",
            name: "numInstallments",
            type: "uint24",
          },
          {
            internalType: "uint160",
            name: "interestRate",
            type: "uint160",
          },
          {
            internalType: "uint256",
            name: "principal",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "collateralAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "collateralId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payableCurrency",
            type: "address",
          },
        ],
        indexed: false,
        internalType: "struct LoanLibrary.LoanTerms",
        name: "terms",
        type: "tuple",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "LoanCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "LoanRepaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldLoanId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newLoanId",
        type: "uint256",
      },
    ],
    name: "LoanRolledOver",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "lender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
    ],
    name: "LoanStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint160",
        name: "nonce",
        type: "uint160",
      },
    ],
    name: "NonceUsed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "feeController",
        type: "address",
      },
    ],
    name: "SetFeeController",
    type: "event",
  },
  {
    inputs: [],
    name: "borrowerNote",
    outputs: [
      {
        internalType: "contract IPromissoryNote",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint160",
        name: "nonce",
        type: "uint160",
      },
    ],
    name: "cancelNonce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentInstallmentPeriod",
        type: "uint256",
      },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint160",
        name: "nonce",
        type: "uint160",
      },
    ],
    name: "consumeNonce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "feeController",
    outputs: [
      {
        internalType: "contract IFeeController",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "getLoan",
    outputs: [
      {
        components: [
          {
            internalType: "enum LoanLibrary.LoanState",
            name: "state",
            type: "uint8",
          },
          {
            internalType: "uint24",
            name: "numInstallmentsPaid",
            type: "uint24",
          },
          {
            internalType: "uint160",
            name: "startDate",
            type: "uint160",
          },
          {
            components: [
              {
                internalType: "uint32",
                name: "durationSecs",
                type: "uint32",
              },
              {
                internalType: "uint32",
                name: "deadline",
                type: "uint32",
              },
              {
                internalType: "uint24",
                name: "numInstallments",
                type: "uint24",
              },
              {
                internalType: "uint160",
                name: "interestRate",
                type: "uint160",
              },
              {
                internalType: "uint256",
                name: "principal",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "collateralAddress",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "collateralId",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "payableCurrency",
                type: "address",
              },
            ],
            internalType: "struct LoanLibrary.LoanTerms",
            name: "terms",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "balance",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "balancePaid",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lateFeesAccrued",
            type: "uint256",
          },
        ],
        internalType: "struct LoanLibrary.LoanData",
        name: "loanData",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint160",
        name: "nonce",
        type: "uint160",
      },
    ],
    name: "isNonceUsed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lenderNote",
    outputs: [
      {
        internalType: "contract IPromissoryNote",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "repay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_loanId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_currentMissedPayments",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_paymentToPrincipal",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_paymentToInterest",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_paymentToLateFees",
        type: "uint256",
      },
    ],
    name: "repayPart",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "oldLoanId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        internalType: "address",
        name: "lender",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint32",
            name: "durationSecs",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "deadline",
            type: "uint32",
          },
          {
            internalType: "uint24",
            name: "numInstallments",
            type: "uint24",
          },
          {
            internalType: "uint160",
            name: "interestRate",
            type: "uint160",
          },
          {
            internalType: "uint256",
            name: "principal",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "collateralAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "collateralId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payableCurrency",
            type: "address",
          },
        ],
        internalType: "struct LoanLibrary.LoanTerms",
        name: "terms",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "_settledAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amountToOldLender",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amountToLender",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amountToBorrower",
        type: "uint256",
      },
    ],
    name: "rollover",
    outputs: [
      {
        internalType: "uint256",
        name: "newLoanId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "lender",
        type: "address",
      },
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint32",
            name: "durationSecs",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "deadline",
            type: "uint32",
          },
          {
            internalType: "uint24",
            name: "numInstallments",
            type: "uint24",
          },
          {
            internalType: "uint160",
            name: "interestRate",
            type: "uint160",
          },
          {
            internalType: "uint256",
            name: "principal",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "collateralAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "collateralId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "payableCurrency",
            type: "address",
          },
        ],
        internalType: "struct LoanLibrary.LoanTerms",
        name: "terms",
        type: "tuple",
      },
    ],
    name: "startLoan",
    outputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILoanCore__factory {
  static readonly abi = _abi;
  static createInterface(): ILoanCoreInterface {
    return new utils.Interface(_abi) as ILoanCoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILoanCore {
    return new Contract(address, _abi, signerOrProvider) as ILoanCore;
  }
}
