/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArcadeMerkleRewards } from "./ArcadeMerkleRewards";
export type { NFTBoostVaultStorage } from "./NFTBoostVaultStorage";
