/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface NFTBoostVaultStorageInterface extends utils.Interface {
  functions: {
    "MULTIPLIER_TYPEHASH()": FunctionFragment;
    "REGISTRATION_TYPEHASH()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "MULTIPLIER_TYPEHASH" | "REGISTRATION_TYPEHASH"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MULTIPLIER_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRATION_TYPEHASH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MULTIPLIER_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRATION_TYPEHASH",
    data: BytesLike
  ): Result;

  events: {};
}

export interface NFTBoostVaultStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NFTBoostVaultStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MULTIPLIER_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    REGISTRATION_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;
  };

  MULTIPLIER_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  REGISTRATION_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    MULTIPLIER_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    REGISTRATION_TYPEHASH(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    MULTIPLIER_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    REGISTRATION_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MULTIPLIER_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    REGISTRATION_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
