/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IARCDVestingVault } from "./IARCDVestingVault";
export type { IArcadeCoreVoting } from "./IArcadeCoreVoting";
export type { IArcadeToken } from "./IArcadeToken";
export type { IArcadeTreasury } from "./IArcadeTreasury";
export type { IBadgeDescriptor } from "./IBadgeDescriptor";
export type { IBaseVotingVault } from "./IBaseVotingVault";
export type { INFTBoostVault } from "./INFTBoostVault";
export type { IReputationBadge } from "./IReputationBadge";
