/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BadgeDescriptor__factory } from "./BadgeDescriptor__factory";
export { ReputationBadge__factory } from "./ReputationBadge__factory";
