/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BadgeDescriptor } from "./BadgeDescriptor";
export type { ReputationBadge } from "./ReputationBadge";
